package st20048261;

import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import org.apache.logging.log4j.LogManager;
/**
 * This class generates and manipulates the user interface
 * @author paulobalbino
 */
public class GUI extends javax.swing.JFrame {
    private final List<Tweet> tweetList = TwitterSentiment.list();
    static org.apache.logging.log4j.Logger log = LogManager.getLogger(GUI.class.getName());
   
    /**
     * The constructor of the class,it initialises the components
     * @throws Exception 
     */
    public GUI() throws Exception {
        initComponents();
        log.debug("Components of the GUI initialized");
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        TweetsPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableTweets = new javax.swing.JTable();
        MapsPane = new javax.swing.JPanel();
        mapLabel = new javax.swing.JLabel();
        chartPanel = new javax.swing.JPanel();
        chartLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        TableTweets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Location", "Date", "Sentiment Rating", "Area", "Tweet"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableTweets.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TableTweets);

        javax.swing.GroupLayout TweetsPaneLayout = new javax.swing.GroupLayout(TweetsPane);
        TweetsPane.setLayout(TweetsPaneLayout);
        TweetsPaneLayout.setHorizontalGroup(
            TweetsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TweetsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        TweetsPaneLayout.setVerticalGroup(
            TweetsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TweetsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tweets", TweetsPane);
        TweetsPane.getAccessibleContext().setAccessibleName("TweetsTab");
        TweetsPane.getAccessibleContext().setAccessibleDescription("");

        mapLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mapLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout MapsPaneLayout = new javax.swing.GroupLayout(MapsPane);
        MapsPane.setLayout(MapsPaneLayout);
        MapsPaneLayout.setHorizontalGroup(
            MapsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mapLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MapsPaneLayout.setVerticalGroup(
            MapsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mapLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Map", MapsPane);

        chartLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout chartPanelLayout = new javax.swing.GroupLayout(chartPanel);
        chartPanel.setLayout(chartPanelLayout);
        chartPanelLayout.setHorizontalGroup(
            chartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chartLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        chartPanelLayout.setVerticalGroup(
            chartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chartLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chart", chartPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("MapTab");

        setBounds(0, 0, 754, 568);
    }// </editor-fold>//GEN-END:initComponents


    public JTable getTableTweets() {
        return TableTweets;
    }

    public void setTableTweets(JTable TableTweets) {
        this.TableTweets = TableTweets;
    }

    public JLabel getChartLabel() {
        return chartLabel;
    }

    public void setChartLabel(JLabel chartLabel) {
        this.chartLabel = chartLabel;
    }

    public JLabel getMapLabel() {
        return mapLabel;
    }

    public void setMapLabel(JLabel mapLabel) {
        this.mapLabel = mapLabel;
    }

    public JPanel getMapsPane() {
        return MapsPane;
    }

    public void setMapsPane(JPanel MapsPane) {
        this.MapsPane = MapsPane;
    }

    public JPanel getTweetsPane() {
        return TweetsPane;
    }

    public void setTweetsPane(JPanel TweetsPane) {
        this.TweetsPane = TweetsPane;
    }

    public JPanel getChartPanel() {
        return chartPanel;
    }

    public void setChartPanel(JPanel chartPanel) {
        this.chartPanel = chartPanel;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MapsPane;
    private javax.swing.JTable TableTweets;
    private javax.swing.JPanel TweetsPane;
    private javax.swing.JLabel chartLabel;
    private javax.swing.JPanel chartPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mapLabel;
    // End of variables declaration//GEN-END:variables
}
